eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8820/eureka/

server:
  port: 8840
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:8810

zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service