eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8820/eureka/
server:
  port: 8810
spring:
  application:
    name: zipkin-server
management:
  metrics:
    web:
      server:
        auto-time-requests: false